### ISSUE TITLE
python version on readme

### ISSUE THREAD

**Issue by Borgotto** [expl0r3rgu1/kalogero#5]
Change the text on the [README.md](https://github.com/expl0r3rgu1/kalogero/blob/main/README.md) from `Python v3` to `Python3.6+` or `Python 3.6 or newer`.
Also add a url to the download page of python as good practice
( via markdown `(Python3.6+)[https://www.python.org/downloads/]` )

**Comment by expl0r3rgu1** [comment]
Will be done soon. Thanks for the suggestion!
